### ISSUE TITLE
do not check for null

### ISSUE THREAD

**Issue by ignatandrei** [ThomasBleijendaal/GeneratedMapper#10]
The code for checks for null and throws exception. I do not know why, but I do not think that is the problem of generated code- it is the problem of the resolver /  propery.

Example of code:

       Name = (self.Name ?? throw new GeneratedMapper.Exceptions.PropertyNullException("DTOMapper.Department -> DTOMapper.DepartmentDTO: Property Name is null.")),
                EmployeesNr = resolverLength.Resolve((self.Employees ?? throw new GeneratedMapper.Exceptions.PropertyNullException("DTOMapper.Department -> DTOMapper.DepartmentDTO: Property Employees is null."))),
         
What I want:
       Name = self.Name 
EmployeesNr = resolverLength.Resolve(self.Employees )

**Comment by ThomasBleijendaal** [comment]
If you map from `string` to `string`, the mapper will do a null check to prevent the null from propagating beyond the mapper. If you correctly annotate for null, so mapping from `string` to `string?`, or `string?` to `string?`, the mapper will not add null-checks. 

If you want to disable this behavior, please check [the configuration document](https://github.com/ThomasBleijendaal/GeneratedMapper#configuration) to disable the checks using `[assembly: MapperGeneratorConfiguration(ThrowWhenNotNullablePropertyIsNull = false)]`.
