### ISSUE TITLE
add partial

### ISSUE THREAD

**Issue by ignatandrei** [ThomasBleijendaal/GeneratedMapper#9]
please add a partial
public static void AfterCopy( < type of the object> t , <type oif the objet> original )

to let the user customize further the copy process

**Comment by ThomasBleijendaal** [comment]
Good idea. Version 2.2 should have that feature now, you need to enable it using `[assembly: MapperGeneratorConfiguration(GenerateAfterMapPartial = true)]`.

**Comment by ignatandrei** [comment]
Thanks. Let me know.

**Comment by ThomasBleijendaal** [comment]
New package should be up.
